jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - bash: |
          python3 ./tools/sqf_validator.py
        displayName: 'Validate SQF'
      - bash: |
          python3 ./tools/stringtable_validator.py
        displayName: 'Validate Stringtables'
  - job: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - powershell: |
          ./tools/getArmake.ps1
        displayName: 'Install armake'
      - bash: |
          make releaseCI
        displayName: 'Build with armake'
      - powershell: |
          ls *.tar.gz
          mv (ls *.tar.gz).Name $(Build.ArtifactStagingDirectory)
          ls $(Build.ArtifactStagingDirectory)
        displayName: 'Move tar to Artifact Directory'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: release
