name: Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Validate Return Types
      run: python3 tools/return_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build with HEMTT
        uses: arma-actions/hemtt@master
        with:
          command: build --release --ci
  notify:
    needs: [validate, build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Rezent
        env:
          REZENT_TOKEN: ${{ secrets.REZENT_TOKEN }}
          REZENT_URI: ${{ secrets.REZENT_URI }}
        if: always()
        run: |
          curl -H "Authorization: Bearer ${REZENT_TOKEN}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -X POST \
            -d '{"organisation": "zen-mod", "repository": "ZEN", "workflow_id": 650750}' \
            "$REZENT_URI"
